# Generated by Django 4.0.6 on 2022-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_productcategory_comment_bid_auction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('NONSPECIFIC', 'Nonspecific'), ('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('ELECTRONICS', 'Electronics'), ('HOME', 'Home')], default=('NONSPECIFIC', 'Nonspecific'), max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='init_bid',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
