# Generated by Django 4.0.6 on 2022-08-21 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_bids_alter_auction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bids',
            field=models.ManyToManyField(blank=True, through='auctions.Bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
